services:

  pahar-theke:
    container_name: Pahar-Theke-Ecomerce
    build: .
    volumes:
      - '.:/var/www/html'
    ports:
      - 9004:80
  
  mysql_db_pahar_theke:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      APP_DEBUG: true
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 1001:3306
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1